# Generated by Django 6.0.4 on 2026-04-24 11:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True)),
                ('tavsif', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('qoshilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('user_holati', models.BooleanField(default=True)),
                ('oxirgi_faollik', models.DateTimeField(auto_now=True)),
                ('email_tasdiqlanganmi', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.rol')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('familiya', models.CharField(max_length=20)),
                ('avatar', models.ImageField(default='avatar/default.png', upload_to='avatar')),
                ('university', models.CharField(blank=True, max_length=200)),
                ('fakultet', models.CharField(blank=True, max_length=200)),
                ('kurs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('manzil', models.CharField(blank=True, max_length=200)),
                ('bio_text', models.TextField(blank=True, null=True)),
                ('ish_sohasi', models.CharField(blank=True, max_length=200, null=True)),
                ('tashriflar_soni', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loyihalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('tavsif', models.TextField(blank=True, max_length=500, null=True)),
                ('avatar', models.ImageField(default='projectpicture/default.png', upload_to='projectpicture')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_link', models.URLField(blank=True, null=True)),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('video', models.URLField(blank=True, null=True)),
                ('korishlar_soni', models.PositiveSmallIntegerField(default=0)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.profil')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['yaratilgan_sana'],
            },
        ),
        migrations.CreateModel(
            name='Ish_faoliyati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kompaniya', models.CharField(max_length=200)),
                ('lavozim', models.CharField(max_length=200)),
                ('ish_turi', models.CharField(choices=[('stajirovka', 'Stajirovka (Internship)'), ('frilans', 'Frilans'), ('full_time', "To'liq stavka (Full-time)"), ('part_time', 'Yarim stavka (Part-time)')], default='stajirovka', max_length=50)),
                ('tavsif', models.TextField(blank=True, null=True)),
                ('boshlangan_sana', models.DateField()),
                ('tugatilgan_sana', models.DateField(blank=True, null=True)),
                ('yuklangan_sana', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ishlari', to='mainapp.profil')),
            ],
            options={
                'verbose_name': 'Ish faoliyati',
                'verbose_name_plural': 'Ish faoliyatlari',
                'ordering': ['yuklangan_sana'],
            },
        ),
        migrations.CreateModel(
            name='Faol_tarmoqlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=100, null=True)),
                ('manzil', models.URLField(max_length=255)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarmoqlari', to='mainapp.profil')),
            ],
            options={
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
            },
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('bergan_tashkilot', models.CharField(blank=True, max_length=100, null=True)),
                ('fayl_isbot', models.FileField(upload_to='fayl_isbot/%Y/%m/')),
                ('olingan_sana', models.DateTimeField()),
                ('yuklash_sanasi', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertifikat', to='mainapp.profil')),
            ],
            options={
                'verbose_name': 'Sertifikatlar',
                'verbose_name_plural': 'Sertifikat',
                'ordering': ['yuklash_sanasi'],
            },
        ),
        migrations.CreateModel(
            name='Tadbirlar_va_yutuqlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('roli', models.CharField(choices=[('golib', "G'olib"), ('ishtirokchi', 'Ishtirokchi'), ('spiker', 'Spiker'), ('tashkilotchi', 'Tashkilotchi')], default='ishtirokchi', max_length=100)),
                ('yuklangan_sanasi', models.DateTimeField(auto_now_add=True)),
                ('bolib_otgan_sanasi', models.DateTimeField(blank=True, null=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tadbirlar', to='mainapp.profil')),
            ],
            options={
                'verbose_name': 'Tadbirlar va yutuqlar',
                'verbose_name_plural': 'Tadbirlar/Yutuqlar',
                'ordering': ['yuklangan_sanasi'],
            },
        ),
    ]
