# Generated by Django 6.0.4 on 2026-04-24 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_users_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyihalar',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyihalar', to='mainapp.profil'),
        ),
    ]
