# Generated by Django 6.0.4 on 2026-04-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_loyihalar_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sertifikat',
            options={'ordering': ['yuklash_sanasi'], 'verbose_name': 'Sertifikatlar', 'verbose_name_plural': 'Sertifikatlar'},
        ),
        migrations.AddField(
            model_name='tadbirlar_va_yutuqlar',
            name='fotolavha',
            field=models.ImageField(default='tadbirdanlavha/default.png', upload_to='tadbirdanlavha'),
        ),
    ]
