# Generated by Django 6.0.4 on 2026-04-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_sertifikat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ish_faoliyati',
            name='fotolavha',
            field=models.ImageField(default='tadbirdanlavha/default.png', upload_to='tadbirdanlavha'),
        ),
    ]
