# Generated by Django 6.0.4 on 2026-04-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_ish_faoliyati_fotolavha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tadbirlar_va_yutuqlar',
            name='tavsif',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
