# Generated by Django 6.0.4 on 2026-04-25 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_tadbirlar_va_yutuqlar_tavsif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tadbirlar_va_yutuqlar',
            name='fotolavha',
        ),
        migrations.CreateModel(
            name='TadbirRasmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='tadbir_rasmlari/')),
                ('tadbir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlari', to='mainapp.tadbirlar_va_yutuqlar')),
            ],
        ),
    ]
