# Generated by Django 6.0.4 on 2026-04-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_tadbirlar_va_yutuqlar_fotolavha_tadbirrasmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ish_faoliyati',
            name='fotolavha',
            field=models.ImageField(default='ishdanlavha/default.png', upload_to='ishdanlavha'),
        ),
    ]
